### ISSUE TITLE
Cannot find module 'walk-sync'

### ISSUE THREAD

**Issue by jish** [chancancode/hn-reader#1]
Following the instructions in the readme:
- clone
- `npm install`
- `bower install`
- `ember server`

https://github.com/chancancode/hn-reader#installation

I get the following output

```
edge/hn-reader[master]% ember server
version: 0.1.12
Cannot find module 'walk-sync'
Error: Cannot find module 'walk-sync'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/josh/code/js/edge/hn-reader/lib/fixtures-packer/lib/broccoli-packer.js:3:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by chancancode** [comment]
I think I did something wrong with the in-repo-add-ons (in lib)! You need to cd into each of them and run npm install in those. @stefanpenner do you know why?

**Comment by chancancode** [comment]
I should probably get rid of them anyway, or extract them into proper add ons

**Comment by stefanpenner** [comment]
@jish which version of NPM are you on?

likely solution

```
npm install -g npm #install latest npm
rm -rf node_modules
npm cache clean
npm install
```

**Comment by stefanpenner** [comment]
checking out the app now to see

**Comment by stefanpenner** [comment]
ah, ya in-app addon's package json isn't really supposed to have dependencies, unless you ad a script to handle that,we don't support it out of the box.

**Comment by chancancode** [comment]
@stefanpenner great! so I should move those dependencies to the root package.json, right? (at least until I get rid of those)

Related #6

**Comment by stefanpenner** [comment]
unsure, but i added this: https://github.com/chancancode/hn-reader/pull/4

**Comment by chancancode** [comment]
Cool, @jish, so I think that fixes the problem! Let me (us?) know if it's not the case :smile:

**Comment by jish** [comment]
```
$ npm --version
2.1.9
$ npm install -g npm
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
npm@2.6.1 /usr/local/lib/node_modules/npm
$ npm --version
2.6.1
$ rm -rf node_modules
$ npm cache clean
$ npm install
```

Gives the same error

```
$ cd lib/fixtures-packer
$ npm install
$ cd ../sass-assets
$ npm install
$ cd ../..
$ ember server
```

Works. Thanks! :)
